name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      # Run migrations with error handling
      - name: Apply database migrations
        run: |
          echo "Starting database migrations..."
          npx prisma migrate deploy
          if [ $? -eq 0 ]; then
            echo "Migrations completed successfully"
          else
            echo "Migration failed"
            exit 1
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Verify database connection and tables
      - name: Verify database setup
        run: |
          echo "Verifying database connection..."
          npx prisma db pull
          if [ $? -eq 0 ]; then
            echo "Database connection verified"
          else
            echo "Database connection failed"
            exit 1
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Add a delay to ensure migrations complete
      - name: Wait for migrations
        run: |
          echo "Waiting for migrations to settle..."
          sleep 15
          echo "Proceeding with build"

      # Install Vercel CLI after migrations
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Pull environment variables after migrations
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Pass DATABASE_URL to build step
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}